<a href="https://colab.research.google.com/github/gitmystuff/DTSC4050/blob/main/Week_12-Classification_I/Data_Science_Fiction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science Fiction

Please help me write an overview for a science fiction disaster

## Neon Crash: A Symphony of Destruction

**Setting:** New Shanghai, 2077. A glittering metropolis built on reclaimed swampland, where neon lights pierce the perpetual twilight and towering arcologies scrape the smog-choked sky.

**Disaster:**  The year is 2077, and humanity's gamble on hyper-efficient fusion power takes a nightmarish turn. A routine maintenance procedure on the city's central reactor triggers a cascade failure, causing a chain reaction that rips a hole in the fabric of reality. This "Neon Tear" unleashes a torrent of raw energy, warping gravity and bathing the city in an otherworldly glow.

**Characters:**

* **Dr. Anya Petrova:** A brilliant but jaded physicist working at the fusion plant. Haunted by past mistakes, she becomes a reluctant hero when the disaster unfolds.
* **Lin "Razor" Wei:** A cunning streetwise smuggler with a heart of gold. He becomes Anya's unlikely partner as they navigate the crumbling cityscape, searching for a way to contain the Neon Tear.
* **Mayor Tanaka Sato:** A ruthless politician desperate to maintain control amidst the chaos. His hidden motives and thirst for power could spell further disaster for New Shanghai.

**Story Arc:** Anya and Lin must race against time to understand the physics of the tear and find a way to stabilize it before it consumes the entire city. As they delve deeper into the heart of the disaster zone, they face not only the warped physics of the tear but also the rising tide of anarchy and desperation that grips New Shanghai.

**Themes:**  This story explores themes of human hubris in the face of scientific advancement, the resilience of the human spirit in the face of disaster, and the blurred lines between heroism and opportunism in a desperate situation.

Please help me write an overview for a science fiction disaster about people who die or survive

## Title  

(Here's where you fill in a title that captures the essence of your story!)

**Overview:**

In the year 2142, humanity's hubris leads to a cataclysmic event. Project Lazarus, a daring experiment to achieve interstellar travel by manipulating gravity, malfunctions spectacularly. The delicate balance of Earth's atmosphere is fractured, unleashing a cascade of global disasters.  

**The Culling:**

- Solar flares rip through the ozone layer, bathing the planet in lethal UV radiation.
- Violent storms churn across continents, leaving devastation in their wake.
- Cities become irradiated wastelands, and food production plummets.

**Survival of the Fittest:**

- A desperate scramble for survival ensues. The wealthy elite, with advanced shelters and stockpiled resources, retreat into a life of paranoid luxury.
- The unprepared masses face the harsh reality of a dying world. Survival hinges on ingenuity, resourcefulness, and the formation of small, fiercely independent communities.

**The Survivors:**

- Ava, a brilliant but ostracized astrophysicist, blames herself for Project Lazarus' failure. Now, haunted by guilt and determined to atone, she joins a ragtag group of survivors.
- Kai, a hardened scavenger with a mysterious past, possesses the skills needed to navigate the ravaged landscape. He leads a band of misfits, each with their own reason to fight for a future that seems ever more bleak.

**The Choice:**

- As Ava and Kai's paths collide, they unearth a dark secret buried within the ruins of Project Lazarus. This discovery offers a glimmer of hope – a potentially life-saving technology. But using it comes with a devastating price.

**Will the survivors choose to save themselves, or gamble on a desperate attempt to heal a broken Earth?**

Please help me write an overview for a science fiction disaster about people who die or survive based on their characteristics

## The Harmonic: A Symphony of Survival

The world fractures in a deafening silence. No explosions, no warnings, just a sudden, chilling quiet. Humanity is plunged into chaos as a mysterious alien signal washes over the planet. This isn't a random attack; it's a culling. The signal resonates differently with each person, triggering a biological response. The strong-willed, the adaptable, the curious - they survive, their bodies humming in harmony with the alien frequency. The others, the fearful, the rigid, the complacent - they simply… cease.

Aisha, a streetwise scavenger with a rebellious streak, finds herself immune. But her world is shattered. Her stoic grandfather, a pillar of her life, falls victim. Her once bustling city becomes a graveyard of the incompatible. Now, she must navigate a landscape fractured by grief and paranoia.

Meanwhile, Dr. Kai Tanaka, a disgraced geneticist ostracized for his unorthodox theories, becomes humanity's unlikely savior. He recognizes the signal for what it is - a test. A search for a specific human trait. But what is it? And how can they use it to their advantage?

Aisha and Kai, an unlikely duo bound by loss and a desperate hope, join forces. They must race against time to decipher the alien message and unlock the key to survival. Their journey takes them through desolate wastelands, into hidden enclaves of the ostracized who may hold the answer, and face to face with ruthless survivors who see this as a chance to seize power.

Will they find the harmonic note that resonates with humanity's core, or will the Earth become a silent tomb for those who can't adapt? The Harmonic is a story of resilience, of finding strength in the unexpected, and the fight to survive in a world where your very essence determines your fate.

Please help me write an overview for a science fiction disaster about people who die or survive based on their characteristics and habits

## The Harmony Purge

**Overview:**

The year is 2047. Humanity has reached a tipping point. Pollution, resource depletion, and social unrest threaten to unravel civilization. Enter the Harbingers, a mysterious alien race who arrive with a seemingly benevolent solution: The Harmony Purge.

The Purge isn't a weapon, but a bio-scan. It analyzes a person's genetic makeup, brainwaves, and even their digital footprint – their social media habits, health records, and daily routines. Based on this data, the Harbingers declare who is "compatible" with their vision for a sustainable future. The incompatible – the chronically stressed, the environmentally destructive, the emotionally volatile – simply… cease to exist.

**The Survivors:**

The world is left reeling. Cities are eerily empty, luxury apartments stand abandoned beside thriving community gardens. Sarah, a reclusive writer known for her introspective nature and focus on self-sufficiency, finds herself inexplicably spared. John, a former corporate raider with a cutthroat business strategy and unhealthy lifestyle, lies cold on his office floor.

**The Factions:**

As the survivors grapple with the new reality, two factions emerge: the Harmonious, who believe their compliance was rewarded, and the Discordant, those who see the Harbingers as invaders manipulating humanity. Sarah, caught between both sides, uncovers a hidden message in the Harbingers' data stream. It hints at a more sinister purpose behind the Purge, one that could mean extinction for all humankind.

**The Stakes:**

Sarah must decipher the message and unite the fractured society. Can the survivors overcome their differences before the Harbingers enact their true plan? Or will humanity become another casualty of a universe obsessed with order?

**Themes:**

* The Harmony Purge explores themes of environmentalism, social responsibility, and the nature of humanity.
* It asks questions about the choices we make and the impact they have on ourselves and the planet.
* It examines the cost of conformity and the power of resilience in a world turned upside down.

## The Data

In [1]:
# pip install Faker

In [2]:
state_names=["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

In [3]:
# https://stackoverflow.com/questions/65678496/linking-first-name-and-gender-in-faker-library
# https://stackoverflow.com/questions/20638006/convert-list-of-dictionaries-to-a-pandas-dataframe
# https://www.quora.com/What-are-some-different-perspectives-to-view-gender
import numpy as np
import pandas as pd
from faker import Faker
fake = Faker()

output = []
for x in range(100):
  sex = np.random.choice(['egg', 'seed'], p=[0.5, 0.5])
  output.append(
    {
        'sex': sex,
        'brain_wave': np.random.choice(['BETA', 'ALPHA', 'THETA']),
        'given_name': fake.first_name_female() if sex=='egg' else fake.first_name_male(),
        'surname': fake.last_name(),
        'zipcode': fake.zipcode(),
        'date_of_birth': fake.date_of_birth(),
        'state': np.random.choice(state_names),
        })

demographics = pd.DataFrame(output)
demographics.head()

   sex brain_wave given_name   surname zipcode date_of_birth          state
0  egg       BETA  Christine    Martin   15910    1948-07-31    Mississippi
1  egg      THETA     Sherry     Owens   02135    1937-02-21  Massachusetts
2  egg      THETA     Deanna    Walton   21339    1955-03-15         Kansas
3  egg       BETA     Tracie  Mcknight   19486    1926-01-12         Hawaii
4  egg       BETA     Nicole   Salazar   71640    2007-07-28   Rhode Island

In [4]:
import pandas as pd
import numpy as np
import random
import re
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt

def make_null(r, w):
    rtn = random.choices([np.nan, r], weights=[w, 100-w])
    return re.sub(r"[\[\]]",'', str(rtn))

# unpacking
features, binary_class = make_classification(n_samples=100, n_features=6,
                                             n_informative=2, n_redundant=2,
                                             n_repeated=2,
                                             n_clusters_per_class=1, random_state=42)


cols = ['chron_dist', 'env_destr', 'emot_vol', 'ingenuity', 'resourcefulness', 'collaboration']
random.shuffle(cols)
df = pd.DataFrame(data=features, columns=cols)
df['earth'] = round(df[cols[0]], 2)
df['mars'] = df['earth']
df['moon_col_2'] = 0.03
df['moon_col_1'] = 0.07

df[cols[0]] = df[cols[0]].apply(lambda r: abs(r) if (r < -0.02) else r)
df[cols[1]] = df[cols[1]].apply(lambda r: abs(r)*-1 if (r > 0.01) else r)
df[cols[2]] = df[cols[2]].apply(lambda r: abs(r) if (r < -0.01) else r)

df['jupiter'] = random.sample(range(10000, 30000), 100)
df['saturn'] = random.sample(range(1000, 3000), 100)
df[cols[3]] = df[cols[3]].apply(make_null, args=(3,))
df[cols[4]] = df[cols[4]].apply(make_null, args=(4,))
df[cols[5]] = df[cols[5]].apply(make_null, args=(5,))

df = df[np.random.default_rng().permutation(df.columns.values)]
df = pd.concat([df, demographics], axis=1)
df['sex'] = df['sex'].apply(make_null, args=(5,))
df['state'] = df['state'].apply(make_null, args=(5,))
df['class'] = binary_class

dupes = df.loc[0:7]
df = pd.concat([df, dupes], axis=0)
df = df.sample(frac=1).reset_index(drop=True)

df.to_csv('data_science_fiction.csv')

print(df.shape)
print(df.info())
df.head()

(108, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   chron_dist       108 non-null    float64
 1   ingenuity        108 non-null    object
 2   env_destr        108 non-null    float64
 3   saturn           108 non-null    int64
 4   emot_vol         108 non-null    float64
 5   jupiter          108 non-null    int64
 6   collaboration    108 non-null    object
 7   earth            108 non-null    float64
 8   moon_col_1       108 non-null    float64
 9   resourcefulness  108 non-null    object
 10  moon_col_2       108 non-null    float64
 11  mars             108 non-null    float64
 12  sex              108 non-null    object
 13  brain_wave       108 non-null    object
 14  given_name       108 non-null    object
 15  surname          108 non-null    object
 16  zipcode          108 non-null    object
 17  date_of_birth    108 non-null    object
 18  state            108 non-null    object
 19  class            108 non-null    int64
dtypes: float64(7), int64(3), object(10)
memory usage: 17.0+ KB
None

,chron_dist,ingenuity,env_destr,saturn,emot_vol,jupiter,collaboration,earth,moon_col_1,resourcefulness,moon_col_2,mars,sex,brain_wave,given_name,surname,zipcode,date_of_birth,state,class
0,1.441463,2.2591175762617537,0.705763,2211,-2.330268,21116,1.4414629075633907,1.44,0.07,1.4414629075633907,0.03,1.44,'egg',BETA,Sara,Morgan,29272,1909-09-17,'Oklahoma',1
1,0.897396,1.3859182227177431,0.439551,2625,-1.451510,11480,0.8973963308381672,0.90,0.07,0.8973963308381672,0.03,0.90,'egg',THETA,Lisa,Gonzalez,38434,1924-06-07,'Illinois',1
2,1.199671,1.8991032088393323,0.587220,1752,-1.938667,28965,1.1996710026473385,1.20,0.07,1.1996710026473385,0.03,1.20,'egg',THETA,Lisa,Haynes,62140,1949-03-26,'Mississippi',1
3,0.441774,-1.243783974468926,0.232509,2283,-0.787792,25836,0.44177384271997205,0.44,0.07,0.44177384271997205,0.03,0.44,'seed',THETA,Sean,Castillo,70695,2001-09-21,'Massachusetts',0
4,0.138188,-0.14928516917504275,0.068222,1145,-0.225952,10799,-0.13818756563029264,-0.14,0.07,-0.13818756563029264,0.03,-0.14,'egg',ALPHA,Jessica,Henderson,04731,1931-04-09,'Iowa',1

In [5]:
import pandas as pd

df = pd.read_csv('data_science_fiction.csv', index_col=0)
print(df.shape)
print(df.info())
df.head()

(108, 20)
<class 'pandas.core.frame.DataFrame'>
Index: 108 entries, 0 to 107
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   chron_dist       108 non-null    float64
 1   ingenuity        103 non-null    float64
 2   env_destr        108 non-null    float64
 3   saturn           108 non-null    int64
 4   emot_vol         108 non-null    float64
 5   jupiter          108 non-null    int64
 6   collaboration    106 non-null    float64
 7   earth            108 non-null    float64
 8   moon_col_1       108 non-null    float64
 9   resourcefulness  98 non-null     float64
 10  moon_col_2       108 non-null    float64
 11  mars             108 non-null    float64
 12  sex              102 non-null    object
 13  brain_wave       108 non-null    object
 14  given_name       108 non-null    object
 15  surname          108 non-null    object
 16  zipcode          108 non-null    int64
 17  date_of_birth    108 non-null    object
 18  state            101 non-null    object
 19  class            108 non-null    int64
dtypes: float64(10), int64(4), object(6)
memory usage: 17.7+ KB
None

,chron_dist,ingenuity,env_destr,saturn,emot_vol,jupiter,collaboration,earth,moon_col_1,resourcefulness,moon_col_2,mars,sex,brain_wave,given_name,surname,zipcode,date_of_birth,state,class
0,1.441463,2.259118,0.705763,2211,-2.330268,21116,1.441463,1.44,0.07,1.441463,0.03,1.44,'egg',BETA,Sara,Morgan,29272,1909-09-17,'Oklahoma',1
1,0.897396,1.385918,0.439551,2625,-1.451510,11480,0.897396,0.90,0.07,0.897396,0.03,0.90,'egg',THETA,Lisa,Gonzalez,38434,1924-06-07,'Illinois',1
2,1.199671,1.899103,0.587220,1752,-1.938667,28965,1.199671,1.20,0.07,1.199671,0.03,1.20,'egg',THETA,Lisa,Haynes,62140,1949-03-26,'Mississippi',1
3,0.441774,-1.243784,0.232509,2283,-0.787792,25836,0.441774,0.44,0.07,0.441774,0.03,0.44,'seed',THETA,Sean,Castillo,70695,2001-09-21,'Massachusetts',0
4,0.138188,-0.149285,0.068222,1145,-0.225952,10799,-0.138188,-0.14,0.07,-0.138188,0.03,-0.14,'egg',ALPHA,Jessica,Henderson,4731,1931-04-09,'Iowa',1