<a href="https://colab.research.google.com/github/gitmystuff/DTSC4050/blob/main/Week_13-Classification_II/Data_Science_Fiction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science Fiction

Your Name

## The Instructions

* Create a story that has a binary outcome (see the Create Story section)
* Create a dataset by running the cells in the Create Dataset section
* Prepare the dataset (see The Data section)
* Run a logistic regression model on your dataset
* Evaluate the model using an accuracy score, a confusion matrix, and a classification report
* Summarize / discuss your findings

## The Story

### Create Dataset

In [ ]:
pip install Faker

Collecting Faker
  Downloading Faker-24.11.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 6.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->Faker) (1.16.0)
Installing collected packages: Faker
Successfully installed Faker-24.11.0

In [ ]:
state_names=["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

In [ ]:
# https://stackoverflow.com/questions/65678496/linking-first-name-and-gender-in-faker-library
# https://stackoverflow.com/questions/20638006/convert-list-of-dictionaries-to-a-pandas-dataframe
# https://www.quora.com/What-are-some-different-perspectives-to-view-gender
import numpy as np
import pandas as pd
from faker import Faker
fake = Faker()

output = []
for x in range(1000):
  binary = np.random.choice(['binary_1', 'binary_2'], p=[0.5, 0.5])
  output.append(
    {
        'binary': binary,
        'ohe': np.random.choice(['ohe_1', 'ohe_2', 'ohe_3', 'ohe_4']),
        'given_name': fake.first_name_female() if binary=='binary_1' else fake.first_name_male(),
        'surname': fake.last_name(),
        'zipcode': fake.zipcode(),
        'date_of_birth': fake.date_of_birth(),
        'state': np.random.choice(state_names),
        })

demographics = pd.DataFrame(output)
demographics.head()

     binary    ohe given_name     surname zipcode date_of_birth       state
0  binary_1  ohe_1    Natasha   Rodriguez   85188    1920-01-04   Tennessee
1  binary_2  ohe_3       Mark     Johnson   74877    1988-12-14    Arkansas
2  binary_1  ohe_3    Cynthia     Esparza   58160    1969-01-01      Kansas
3  binary_1  ohe_1   Cheyenne     Brennan   69477    1953-10-20  Washington
4  binary_2  ohe_1    Michael  Washington   86795    2022-12-16    Kentucky

In [ ]:
import pandas as pd
import numpy as np
import random
import re
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt

def make_null(r, w):
    rtn = random.choices([np.nan, r], weights=[w, 1000-w])
    return re.sub(r"[\[\]]",'', str(rtn))

# unpacking
features, binary_class = make_classification(n_samples=1000, n_features=6,
                                             n_informative=2, n_redundant=2,
                                             n_repeated=2,
                                             n_clusters_per_class=1, random_state=42)


cols = ['attr_1', 'attr_2', 'attr_3', 'attr_4', 'attr_5', 'attr_6']
random.shuffle(cols)
df = pd.DataFrame(data=features, columns=cols)
df['attr_7'] = round(df[cols[0]], 2)
df['attr_8'] = df['attr_7']
df['attr_9'] = 0.13
df['attr_10'] = pd.NA
df['attr_10'] = df['attr_10'].apply(lambda x: np.random.choice(['label_1', 'label_2'], p=[0.02, 0.98]))

df[cols[0]] = df[cols[0]].apply(lambda r: abs(r) if (r < -0.02) else r)
df[cols[1]] = df[cols[1]].apply(lambda r: abs(r)*-1 if (r > 0.01) else r)
df[cols[2]] = df[cols[2]].apply(lambda r: abs(r) if (r < -0.01) else r)

df['attr_11'] = random.sample(range(10000, 30000), 1000)
df['attr_12'] = random.sample(range(1000, 3000), 1000)
df[cols[0]] = df[cols[0]].apply(make_null, args=(4,))
df[cols[1]] = df[cols[1]].apply(make_null, args=(5,))
df[cols[2]] = df[cols[2]].apply(make_null, args=(6,))
df[cols[3]] = df[cols[3]].apply(make_null, args=(4,))
df[cols[4]] = df[cols[4]].apply(make_null, args=(5,))
df[cols[5]] = df[cols[5]].apply(make_null, args=(6,))

df = df[np.random.default_rng().permutation(df.columns.values)]
df = pd.concat([df, demographics], axis=1)
df['binary'] = df['binary'].apply(make_null, args=(5,))
df['state'] = df['state'].apply(make_null, args=(5,))
df['class'] = binary_class

dupes = df.loc[0:7]
df = pd.concat([df, dupes], axis=0)
df = df.sample(frac=1).reset_index(drop=True)

df.to_csv('my_data_science_fiction_story.csv')

print(df.shape)
print(df.info())
df.head()

(1008, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   attr_12        1008 non-null   int64
 1   attr_9         1008 non-null   float64
 2   attr_5         1008 non-null   object
 3   attr_3         1008 non-null   object
 4   attr_7         1008 non-null   float64
 5   attr_6         1008 non-null   object
 6   attr_11        1008 non-null   int64
 7   attr_4         1008 non-null   object
 8   attr_10        1008 non-null   object
 9   attr_1         1008 non-null   object
 10  attr_2         1008 non-null   object
 11  attr_8         1008 non-null   float64
 12  binary         1008 non-null   object
 13  ohe            1008 non-null   object
 14  given_name     1008 non-null   object
 15  surname        1008 non-null   object
 16  zipcode        1008 non-null   object
 17  date_of_birth  1008 non-null   object
 18  state          1008 non-null   object
 19  class          1008 non-null   int64
dtypes: float64(3), int64(3), object(14)
memory usage: 157.6+ KB
None

,attr_12,attr_9,attr_5,attr_3,attr_7,attr_6,attr_11,attr_4,attr_10,attr_1,attr_2,attr_8,binary,ohe,given_name,surname,zipcode,date_of_birth,state,class
0,2646,0.13,0.870441259099916,0.6315929376428634,-0.87,-1.6364218193867357,26837,-0.870441259099916,label_2,-0.870441259099916,1.5275737058352727,-0.87,'binary_1',ohe_2,Sarah,Reynolds,28580,1938-10-22,'Iowa',0
1,1822,0.13,0.23348484323617358,1.2855073429089774,0.23,-1.6302237203201815,20837,0.23348484323617358,label_2,0.23348484323617358,3.1030896985820156,0.23,'binary_1',ohe_2,Tina,Khan,50585,2019-10-03,'Michigan',0
2,1145,0.13,2.89669373842663,-0.541987769833914,2.90,-3.227353035375648,20845,2.89669373842663,label_2,2.89669373842663,1.3173346803147616,2.90,'binary_1',ohe_4,Lisa,Berg,88614,2000-09-01,'Florida',1
3,1281,0.13,0.9684312829640628,0.19188424467101062,0.97,-0.548384464522459,26796,0.9684312829640628,label_2,0.9684312829640628,0.46037560185243653,0.97,'binary_1',ohe_2,Jasmin,Rivera,36055,2006-05-15,'Nevada',1
4,1199,0.13,1.059848199215605,0.34739132579651294,1.06,-0.4047506819830215,16704,1.059848199215605,label_2,1.059848199215605,0.8355641362576897,1.06,'binary_1',ohe_1,Christy,Pham,62122,2022-12-01,'Delaware',1

In [ ]:
import pandas as pd

df = pd.read_csv('my_data_science_fiction_story.csv', index_col=0)
print(df.shape)
print(df.info())
df.head()

(1008, 20)
<class 'pandas.core.frame.DataFrame'>
Index: 1008 entries, 0 to 1007
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   attr_12        1008 non-null   int64
 1   attr_9         1008 non-null   float64
 2   attr_5         1007 non-null   float64
 3   attr_3         1002 non-null   float64
 4   attr_7         1008 non-null   float64
 5   attr_6         1001 non-null   float64
 6   attr_11        1008 non-null   int64
 7   attr_4         1000 non-null   float64
 8   attr_10        1008 non-null   object
 9   attr_1         1006 non-null   float64
 10  attr_2         1000 non-null   float64
 11  attr_8         1008 non-null   float64
 12  binary         1004 non-null   object
 13  ohe            1008 non-null   object
 14  given_name     1008 non-null   object
 15  surname        1008 non-null   object
 16  zipcode        1008 non-null   int64
 17  date_of_birth  1008 non-null   object
 18  state          1003 non-null   object
 19  class          1008 non-null   int64
dtypes: float64(9), int64(4), object(7)
memory usage: 165.4+ KB
None

,attr_12,attr_9,attr_5,attr_3,attr_7,attr_6,attr_11,attr_4,attr_10,attr_1,attr_2,attr_8,binary,ohe,given_name,surname,zipcode,date_of_birth,state,class
0,2646,0.13,0.870441,0.631593,-0.87,-1.636422,26837,-0.870441,label_2,-0.870441,1.527574,-0.87,'binary_1',ohe_2,Sarah,Reynolds,28580,1938-10-22,'Iowa',0
1,1822,0.13,0.233485,1.285507,0.23,-1.630224,20837,0.233485,label_2,0.233485,3.103090,0.23,'binary_1',ohe_2,Tina,Khan,50585,2019-10-03,'Michigan',0
2,1145,0.13,2.896694,-0.541988,2.90,-3.227353,20845,2.896694,label_2,2.896694,1.317335,2.90,'binary_1',ohe_4,Lisa,Berg,88614,2000-09-01,'Florida',1
3,1281,0.13,0.968431,0.191884,0.97,-0.548384,26796,0.968431,label_2,0.968431,0.460376,0.97,'binary_1',ohe_2,Jasmin,Rivera,36055,2006-05-15,'Nevada',1
4,1199,0.13,1.059848,0.347391,1.06,-0.404751,16704,1.059848,label_2,1.059848,0.835564,1.06,'binary_1',ohe_1,Christy,Pham,62122,2022-12-01,'Delaware',1

### Create Story

* Create an overview of a short story similar to the stories provided in assignment 12
* Base the story on the the variables created in the Create Dataset section
* The story must have a binary outcome such as survived or not, won or lost, will get or won't get, etc.
* This binary outcome's data will be the variable named class' data in your datasat, labeled 0 or 1
* Rename the variables appropriately to fit the story
* Put the overview of your story in the following cell - My Story

### My Story

## The Data

* Use the project we've been working on in Replit to clean and prepare your data
* You can also use https://github.com/gitmystuff/preppy.git
* See PrepPy Functions for an example of the dataset preparation steps

#### PrepPy Functions

* identify_consts
* identify_quasi_consts
* check_row_duplicates
* check_col_duplicates
* do_OHE
* handle_missing_values
* handle_standard_scaler
* handle_minmax_scaler

### Prep Data

### Missing Values

### Descriptive Statistics

### Scaling and Outliers

## Modeling and Evaluation

### Logistic Regression

### Confusion Matrix

### Classification Report

## Summary / Discussion

* Wrapup this assignment by discussing accuracy and the true negatives, false positives, false negatives, and true positives
* Include a summary of the classification report
* These metrics should be used in context of your story